name: Eindex

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # each week

jobs:
  Eindex-job:
    env:
      TZ: Asia/Shanghai
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: eindex/package-lock.json

      - name: Install
        run: |
          cd eindex
          curl -O -L https://github.com/EhTagTranslation/Database/releases/latest/download/db.text.json -s -S --connect-timeout 20 --retry 10 --retry-delay 10
          npm ci
          node index.js

      - name: git
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git add -A
          git diff-index --quiet HEAD && echo "no update" || (echo "update!" && git commit -m "Auto Updated: `date +'%Y-%m-%d %H:%M:%S'`" && git push origin main)
