name: icalendar

on:
  workflow_dispatch:
  schedule:
    - cron: "15 * * * *" # each hour

jobs:
  icalendar-job:
    env:
      TZ: Asia/Shanghai
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: curl
        shell: bash {0}
        run: |
          cd icalendar
          curl https://p66-caldav.icloud.com/published/2/MTAyMTk3MTMxMjExMDIxOXsjasy7WUO0EcKVz7qGEuVjjTlRkgd6WOZM171uxP_u-QM51M24lHzRlAQir-oodDRRTzZeusSLbw0snkZoqI4 -fLo ffxivcn.ics
          curl https://p66-caldav.icloud.com/published/2/MTAyMTk3MTMxMjExMDIxOXsjasy7WUO0EcKVz7qGEuVzSK8L9ZRQYf1sxUFeH1A1a22GJLf6nfk2-CZNYMv5iOxCNlUR-umbJKFWWAUVRp8 -fLo ffxivin.ics

      - name: git
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git add -A
          git diff-index --quiet HEAD && echo "no update" || (echo "update!" && git commit -m "Icalendar: `date +'%Y-%m-%d %H:%M:%S'`" && git push)
