name: rule

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: "0 23 * * *" # at 23:00 per day

jobs:
  rule-job:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: curl & pip & run
        shell: bash {0}
        run: |
          cd rule
          curl "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/{apple,applications,cncidr,direct,gfw,google,greatfire,icloud,lancidr,private,proxy,reject,telegramcidr,tld-not-cn}.txt" --create-dirs -fLo "yaml/#1.yaml"
          pip install pyyaml
          python action.py

      - name: git
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git add -A
          git diff-index --quiet HEAD && echo "no update" || (echo "update!" && git commit -m "Auto Updated: `date +'%Y-%m-%d %H:%M:%S'`" && git push origin main)
